openapi: 3.0.1
tags:
- name: v2.0
- name: v1.3
info:
  title: Quubole API Sepcification
  description: Operations, requests and responses
  version: v2.0
  contact:
    email: support@qubole.com
    name: API Support
    url: http://api.qubole.com/support
servers:
- url: https://api.qubole.com
paths:
  /v1.3/accounts/:
    $ref: ./v1.3/accounts.yaml#/paths/~1v1.3~1accounts~1
  /v1.3/clusters:
    $ref: ./v1.3/clusters.yaml#/paths/~1v1.3~1clusters
  /v2/accounts/:
    $ref: ./v2/accounts.yaml#/paths/~1v2~1accounts~1
  /v2/accounts/{user_id}/1:
    $ref: ./v2/accounts.yaml#/paths/~1v2~1accounts~1{user_id}~11
