# coding: utf-8

"""
    Quubole API Sepcification

    Operations, requests and responses  # noqa: E501

    OpenAPI spec version: v2.0
    Contact: support@qubole.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class CreateClusterRequestFairschedulerSettings(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'default_pool': 'str',
        'fairscheduler_config_xml': 'str'
    }

    attribute_map = {
        'default_pool': 'default_pool',
        'fairscheduler_config_xml': 'fairscheduler_config_xml'
    }

    def __init__(self, default_pool=None, fairscheduler_config_xml=None):  # noqa: E501
        """CreateClusterRequestFairschedulerSettings - a model defined in OpenAPI"""  # noqa: E501

        self._default_pool = None
        self._fairscheduler_config_xml = None
        self.discriminator = None

        if default_pool is not None:
            self.default_pool = default_pool
        if fairscheduler_config_xml is not None:
            self.fairscheduler_config_xml = fairscheduler_config_xml

    @property
    def default_pool(self):
        """Gets the default_pool of this CreateClusterRequestFairschedulerSettings.  # noqa: E501


        :return: The default_pool of this CreateClusterRequestFairschedulerSettings.  # noqa: E501
        :rtype: str
        """
        return self._default_pool

    @default_pool.setter
    def default_pool(self, default_pool):
        """Sets the default_pool of this CreateClusterRequestFairschedulerSettings.


        :param default_pool: The default_pool of this CreateClusterRequestFairschedulerSettings.  # noqa: E501
        :type: str
        """

        self._default_pool = default_pool

    @property
    def fairscheduler_config_xml(self):
        """Gets the fairscheduler_config_xml of this CreateClusterRequestFairschedulerSettings.  # noqa: E501


        :return: The fairscheduler_config_xml of this CreateClusterRequestFairschedulerSettings.  # noqa: E501
        :rtype: str
        """
        return self._fairscheduler_config_xml

    @fairscheduler_config_xml.setter
    def fairscheduler_config_xml(self, fairscheduler_config_xml):
        """Sets the fairscheduler_config_xml of this CreateClusterRequestFairschedulerSettings.


        :param fairscheduler_config_xml: The fairscheduler_config_xml of this CreateClusterRequestFairschedulerSettings.  # noqa: E501
        :type: str
        """

        self._fairscheduler_config_xml = fairscheduler_config_xml

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateClusterRequestFairschedulerSettings):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
