# coding: utf-8

"""
    Quubole API Sepcification

    Operations, requests and responses  # noqa: E501

    OpenAPI spec version: v2.0
    Contact: support@qubole.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class CreateClusterRequestDatadogSettings(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'datadog_api_token': 'str',
        'datadog_app_token': 'str'
    }

    attribute_map = {
        'datadog_api_token': 'datadog_api_token',
        'datadog_app_token': 'datadog_app_token'
    }

    def __init__(self, datadog_api_token=None, datadog_app_token=None):  # noqa: E501
        """CreateClusterRequestDatadogSettings - a model defined in OpenAPI"""  # noqa: E501

        self._datadog_api_token = None
        self._datadog_app_token = None
        self.discriminator = None

        if datadog_api_token is not None:
            self.datadog_api_token = datadog_api_token
        if datadog_app_token is not None:
            self.datadog_app_token = datadog_app_token

    @property
    def datadog_api_token(self):
        """Gets the datadog_api_token of this CreateClusterRequestDatadogSettings.  # noqa: E501


        :return: The datadog_api_token of this CreateClusterRequestDatadogSettings.  # noqa: E501
        :rtype: str
        """
        return self._datadog_api_token

    @datadog_api_token.setter
    def datadog_api_token(self, datadog_api_token):
        """Sets the datadog_api_token of this CreateClusterRequestDatadogSettings.


        :param datadog_api_token: The datadog_api_token of this CreateClusterRequestDatadogSettings.  # noqa: E501
        :type: str
        """

        self._datadog_api_token = datadog_api_token

    @property
    def datadog_app_token(self):
        """Gets the datadog_app_token of this CreateClusterRequestDatadogSettings.  # noqa: E501


        :return: The datadog_app_token of this CreateClusterRequestDatadogSettings.  # noqa: E501
        :rtype: str
        """
        return self._datadog_app_token

    @datadog_app_token.setter
    def datadog_app_token(self, datadog_app_token):
        """Sets the datadog_app_token of this CreateClusterRequestDatadogSettings.


        :param datadog_app_token: The datadog_app_token of this CreateClusterRequestDatadogSettings.  # noqa: E501
        :type: str
        """

        self._datadog_app_token = datadog_app_token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateClusterRequestDatadogSettings):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
