# coding: utf-8

"""
    Quubole API Sepcification

    Operations, requests and responses  # noqa: E501

    OpenAPI spec version: v2.0
    Contact: support@qubole.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class CreateClusterResponseSecuritySettings(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'encrypted_ephemerals': 'bool'
    }

    attribute_map = {
        'encrypted_ephemerals': 'encrypted_ephemerals'
    }

    def __init__(self, encrypted_ephemerals=None):  # noqa: E501
        """CreateClusterResponseSecuritySettings - a model defined in OpenAPI"""  # noqa: E501

        self._encrypted_ephemerals = None
        self.discriminator = None

        if encrypted_ephemerals is not None:
            self.encrypted_ephemerals = encrypted_ephemerals

    @property
    def encrypted_ephemerals(self):
        """Gets the encrypted_ephemerals of this CreateClusterResponseSecuritySettings.  # noqa: E501


        :return: The encrypted_ephemerals of this CreateClusterResponseSecuritySettings.  # noqa: E501
        :rtype: bool
        """
        return self._encrypted_ephemerals

    @encrypted_ephemerals.setter
    def encrypted_ephemerals(self, encrypted_ephemerals):
        """Sets the encrypted_ephemerals of this CreateClusterResponseSecuritySettings.


        :param encrypted_ephemerals: The encrypted_ephemerals of this CreateClusterResponseSecuritySettings.  # noqa: E501
        :type: bool
        """

        self._encrypted_ephemerals = encrypted_ephemerals

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateClusterResponseSecuritySettings):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
