openapi: 3.0.1
info:
  title: Account API
  description: Account operations, requests and responses
  version: "v2"
  contact:
    name: API Support
    url: http://api.qubole.com/support
    email: support@qubole.com
tags:
  - name: Account API
paths:
  api:
    post:
      description: Create account request
      tags:
        - 'v2'
        - 'accounts'
      parameters:
        - $ref: "../common.yaml#/parameters/userAgent"
        - $ref: "../common.yaml#/parameters/authToken"
      operationId: v2.create_account
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateAccountRequest"
            examples:
              "0":
                value: |-
                  {
                      "account":
                        {
                          "name": "Test",
                          "level": "free",
                          "compute_type":"CUSTOMER_MANAGED",
                          "storage_type":"CUSTOMER_MANAGED",
                          "CacheQuotaSizeInGB": 50,
                          "defloc": "$DEFLOC",
                          "acc_key" : "$STORAGE_ACCESS_KEY",
                          "secret" : "$STORAGE_SECRET_KEY",
                          "compute_access_key" : "$COMPUTE_ACCESS_KEY",
                          "compute_secret_key": "$COMPUTE_SECRET_KEY",
                          "idle_cluster_timeout": 3,
                          "idle_session_timeout": 2880,
                          "sub_account_creation": false,
                          "aws_region": "us-east-1"
                        }
                  }
      responses:
        "200":
          description: Success response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateAccountResponse"
        '4XX':
          description: Error in processing request
          $ref: "../common.yaml#/components/responses/RequestError"
        '5XX':
          description: Server error in processing request
          $ref: "../common.yaml#/components/responses/ServerError"
components:
  schemas:
    CreateAccount:
      type: object
      properties:
        name:
          type: string
        level:
          type: string
        compute_type:
          type: string
        storage_type:
          type: string
        CacheQuotaSizeInGB:
          type: integer
        defloc:
          type: string
        storage_access_key:
          type: string
        storage_secret_key:
          type: string
        compute_access_key:
          type: string
        compute_secret_key:
          type: string
        idle_cluster_timeout:
          type: integer
        idle_session_timeout:
          type: integer
        sub_account_creation:
          type: boolean
        aws_region:
          type: string
    CreateAccountRequest:
      type: object
      additionalProperties: false
      properties:
        account:
          $ref: "#/components/schemas/CreateAccount"
      required:
        - account
    CreateAccountResponse:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
        state:
          type: string
        groups:
          type: array
          items:
            type: string
        authentication_token:
          type: string
        account_id:
          type: string
        is_aws_keys_enabled:
          type: boolean
        status:
          type: string
      required:
        - account_id
        - authentication_token
        - groups
        - is_aws_keys_enabled
        - name
        - state
        - status
  securitySchemes:
    $ref: "../common.yaml#/securitySchemes"