# coding: utf-8

"""
    Quubole API Sepcification

    Operations, requests and responses  # noqa: E501

    OpenAPI spec version: v2.0
    Contact: support@qubole.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import qpy
from qpy.api.v1_3_api import V13Api  # noqa: E501
from qpy.rest import ApiException


class TestV13Api(unittest.TestCase):
    """V13Api unit test stubs"""

    def setUp(self):
        self.api = qpy.api.v1_3_api.V13Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_account(self):
        """Test case for create_account

        """
        pass

    def test_create_account_0(self):
        """Test case for create_account_0

        """
        pass

    def test_create_account_1(self):
        """Test case for create_account_1

        """
        pass

    def test_create_cluster(self):
        """Test case for create_cluster

        """
        pass


if __name__ == '__main__':
    unittest.main()
