# coding: utf-8

"""
    Quubole API Sepcification

    Operations, requests and responses  # noqa: E501

    OpenAPI spec version: v2.0
    Contact: support@qubole.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import qpy
from qpy.models.create_cluster_response_ec2_settings import CreateClusterResponseEc2Settings  # noqa: E501
from qpy.rest import ApiException


class TestCreateClusterResponseEc2Settings(unittest.TestCase):
    """CreateClusterResponseEc2Settings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateClusterResponseEc2Settings(self):
        """Test CreateClusterResponseEc2Settings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = qpy.models.create_cluster_response_ec2_settings.CreateClusterResponseEc2Settings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
