# coding: utf-8

"""
    Quubole API Sepcification

    Operations, requests and responses  # noqa: E501

    OpenAPI spec version: v2.0
    Contact: support@qubole.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import qpy
from qpy.models.create_cluster_request_ec2_settings import CreateClusterRequestEc2Settings  # noqa: E501
from qpy.rest import ApiException


class TestCreateClusterRequestEc2Settings(unittest.TestCase):
    """CreateClusterRequestEc2Settings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateClusterRequestEc2Settings(self):
        """Test CreateClusterRequestEc2Settings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = qpy.models.create_cluster_request_ec2_settings.CreateClusterRequestEc2Settings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
