# coding: utf-8

"""
    Quubole API Sepcification

    Operations, requests and responses  # noqa: E501

    OpenAPI spec version: v2.0
    Contact: support@qubole.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import qpy
from qpy.models.create_cluster_request_heterogeneous_instance_config import CreateClusterRequestHeterogeneousInstanceConfig  # noqa: E501
from qpy.rest import ApiException


class TestCreateClusterRequestHeterogeneousInstanceConfig(unittest.TestCase):
    """CreateClusterRequestHeterogeneousInstanceConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateClusterRequestHeterogeneousInstanceConfig(self):
        """Test CreateClusterRequestHeterogeneousInstanceConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = qpy.models.create_cluster_request_heterogeneous_instance_config.CreateClusterRequestHeterogeneousInstanceConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
