# coding: utf-8

"""
    Quubole API Sepcification

    Operations, requests and responses  # noqa: E501

    OpenAPI spec version: v2.0
    Contact: support@qubole.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import qpy
from qpy.models.create_account_request2 import CreateAccountRequest2  # noqa: E501
from qpy.rest import ApiException


class TestCreateAccountRequest2(unittest.TestCase):
    """CreateAccountRequest2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateAccountRequest2(self):
        """Test CreateAccountRequest2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = qpy.models.create_account_request2.CreateAccountRequest2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
