# coding: utf-8

"""
    Quubole API Sepcification

    Operations, requests and responses  # noqa: E501

    OpenAPI spec version: v2.0
    Contact: support@qubole.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import qpy
from qpy.models.create_cluster_request_presto_settings import CreateClusterRequestPrestoSettings  # noqa: E501
from qpy.rest import ApiException


class TestCreateClusterRequestPrestoSettings(unittest.TestCase):
    """CreateClusterRequestPrestoSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateClusterRequestPrestoSettings(self):
        """Test CreateClusterRequestPrestoSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = qpy.models.create_cluster_request_presto_settings.CreateClusterRequestPrestoSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
