# coding: utf-8

"""
    Quubole API Sepcification

    Operations, requests and responses  # noqa: E501

    OpenAPI spec version: v2.0
    Contact: support@qubole.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import qpy
from qpy.models.create_cluster_request_spot_instance_settings import CreateClusterRequestSpotInstanceSettings  # noqa: E501
from qpy.rest import ApiException


class TestCreateClusterRequestSpotInstanceSettings(unittest.TestCase):
    """CreateClusterRequestSpotInstanceSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateClusterRequestSpotInstanceSettings(self):
        """Test CreateClusterRequestSpotInstanceSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = qpy.models.create_cluster_request_spot_instance_settings.CreateClusterRequestSpotInstanceSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
