# coding: utf-8

"""
    Quubole API Sepcification

    Operations, requests and responses  # noqa: E501

    OpenAPI spec version: v2.0
    Contact: support@qubole.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import qpy
from qpy.models.get_account_response2 import GetAccountResponse2  # noqa: E501
from qpy.rest import ApiException


class TestGetAccountResponse2(unittest.TestCase):
    """GetAccountResponse2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetAccountResponse2(self):
        """Test GetAccountResponse2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = qpy.models.get_account_response2.GetAccountResponse2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
