# coding: utf-8

"""
    Quubole API Sepcification

    Operations, requests and responses  # noqa: E501

    OpenAPI spec version: v2.0
    Contact: support@qubole.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import qpy
from qpy.models.create_cluster_response_spot_instance_settings import CreateClusterResponseSpotInstanceSettings  # noqa: E501
from qpy.rest import ApiException


class TestCreateClusterResponseSpotInstanceSettings(unittest.TestCase):
    """CreateClusterResponseSpotInstanceSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateClusterResponseSpotInstanceSettings(self):
        """Test CreateClusterResponseSpotInstanceSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = qpy.models.create_cluster_response_spot_instance_settings.CreateClusterResponseSpotInstanceSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
